# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q6TAFUn_pFIYgyBeYfrQg0tEJw7NPMNM

FINAL ASSESSMENT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#Qn 1:
#a)
df = pd.read_csv("/content/Final Dataset - IPL.csv")
df

#Qn 1:
#b)
info_data = df.info()
description = df.describe()
null_values = df.isna().sum()
print(info_data,"\n")
print(description,"\n")
print(null_values)

#Qn 2:Data Cleaning
#a)
null_values = df.isna().sum()
print(null_values)
#fill_df = df.fillna()
drop = df.dropna()
drop

"""QN 2:a) As we can see above the dataset does not contain any null values. If the dataset contains null values we can either replace it or fill it with mean,median or mode of the dataframe column according to the prbm statement. Or if the no of null values are very low, we can drop them directly using dropna() in pandas library."""

#b)
duplicates = df.duplicated().sum()
duplicates

"""QN 2:b) The data does not have any duplicate values that ensures the data integrity."""

#Qn 3:
numeric_cols = df[['first_ings_score','second_ings_score','first_ings_wkts','second_ings_wkts','margin','highscore']]
print(numeric_cols.describe())
median_1 = numeric_cols['first_ings_score'].median()
median_2 = numeric_cols['second_ings_score'].median()
median_3 = numeric_cols['first_ings_wkts'].median()
median_4 = numeric_cols['second_ings_wkts'].median()
median_5 = numeric_cols['margin'].median()
median_6 = numeric_cols['highscore'].median()
print(median_1,median_2,median_3,median_4,median_5,median_6)
mode_1 = numeric_cols['first_ings_score'].mode()
mode_2 = numeric_cols['second_ings_score'].mode()
mode_3 = numeric_cols['first_ings_wkts'].mode()
mode_4 = numeric_cols['second_ings_wkts'].mode()
mode_5 = numeric_cols['margin'].mode()
mode_6 = numeric_cols['highscore'].mode()
print(mode_1,mode_2,mode_3,mode_4,mode_5,mode_6)
var_1 = numeric_cols['first_ings_score'].var()
var_2 = numeric_cols['second_ings_score'].var()
var_3 = numeric_cols['first_ings_wkts'].var()
var_4 = numeric_cols['second_ings_wkts'].var()
var_5 = numeric_cols['margin'].var()
var_6 = numeric_cols['highscore'].var()
print(var_1,var_2,var_3,var_4,var_5,var_6)
range_1 = numeric_cols['first_ings_score'].max()-numeric_cols['first_ings_score'].min()
range_2 = numeric_cols['second_ings_score'].max()- numeric_cols['second_ings_score'].min()
range_3 = numeric_cols['highscore'].max()-numeric_cols['highscore'].min()
print(range_1,range_2,range_3)

#Qn 4:Data Visualisation
# Bar chart for finding which stadium has highest avg first innings score
df_ven = df.groupby('venue')['first_ings_score'].mean()
df_ven_data = pd.DataFrame(df_ven).sort_values(by='first_ings_score',ascending=False)
df_ven_data.plot(kind='bar',xlabel="Venue",ylabel="First_ings_Scores",color="red")
plt.title("Avg_1st_ings_score")

# Pie chart for first innings wickets percentage
x = df['first_ings_wkts'].value_counts()
plt.figure(figsize=(8,8))
plt.pie(x,autopct="%1.f1%%",startangle=90)
plt.legend(df['first_ings_wkts'])
plt.show()

#
y = df['second_ings_score'].value_counts()
df_1 = pd.DataFrame(y).head(10)
df_1.plot(kind='hist')
plt.xticks(np.arange(df['second_ings_score'].max()-df['second_ings_score'].min()))

#Scatter plot
plt.figure(figsize=(10, 10))
sns.scatterplot(x='second_ings_score', y='venue', data=df.head(20))
# plt.title('')
# plt.xlabel(')
# plt.ylabel('')
plt.show()

#Qn 5:
numeric_cols = df[['first_ings_score','second_ings_score','first_ings_wkts','second_ings_wkts','margin','highscore','toss_des']]
num_corr = numeric_cols.corr()
sns.heatmap(num_corr,annot=True,cmap='inferno')
lis = []
# Impact of toss decision in the game
for i in df['toss_decision']:
  if i=="Field":
    lis.append(0)
  else:
    lis.append(1)
lis
df_lis = pd.DataFrame(lis)
df_lis
df['toss_des'] = df_lis

# df_team = df['match_winner'].unique()
# val=0
# lis = []
# for i in df['match_winner']:
#   if i not in lis:
#     lis.append(val)
#   val+=1

# lis

#Qn 6:
numeric_cols = df[['first_ings_score','second_ings_score','first_ings_wkts','second_ings_wkts','margin','highscore']]

for i in numeric_cols:
  sns.boxplot(df[i])
  plt.title(i)
  plt.ylabel("Values")
  plt.show()

#Qn 7:
df_ven_winners = df.groupby(['venue','match_winner'])['match_winner'].count()
df_ven_winners = pd.DataFrame(df_ven_winners)
print(df_ven_winners)
df_ven_indiv_perform = df.groupby(['venue','top_scorer'])['top_scorer'].count()
print(df_ven_indiv_perform)

#Qn 8:
most_potm = df['player_of_the_match'].value_counts().sort_values(ascending=False)
# print(most_potm)
df_top = df.groupby('top_scorer')['match_winner'].count()
df_top = pd.DataFrame(df_top).sort_values(by='match_winner',ascending=False)
print(df_top)
df_bowl = df.groupby('best_bowling')['match_winner'].count()
df_bowl = pd.DataFrame(df_bowl).sort_values(by='match_winner',ascending=False)
print(df_bowl)

#Qn 9:
df['toss_decision'].value_counts()

"""1. The key insights drawn from this dataset are that venue that had the highest first innings score in avg for all the data is in Eden Gardens,Kolkata and the least first innings avg score is in Narendra modi stadium,Ahmedabad.
2. Jos buttler has grabbed the most no of potm awards as compared to all leading with 7 followed by decock.
3. The leading bowler with most wickets here in the dataset is yuzvendra chahal followed by rashid khan, kudeep yadav. This insight is important to note since the top best bowling comes from three spinners that says the venues are welcome to spin-friendly.
4. Another key important insight is that each venue in mumbai i.e.., there are 5 different grounds in mumbai and the match winner in each venue does not have its home team in the top that tells us that home conditions are not proving to be advantageous for the teams. Only team that had its advantage is Gujarat that won 1 match in their home ground with delhi leading 4 tomes victorious in Mumbai.
5. Another insight to note is that Abishek sharma leads the top scorer chart in 2 different venues in Mumbai.
6. Most teams chose to field first with 59 and batting first with 15 that means most teams prefer to bowl first that tells us that there is a dew condotion that helpos them to win.

"""